[tool.poetry]
name = "tmo"
version = "0.1.0"
description = ""
authors = ["Brendan Cazier <520246+cazier@users.noreply.github.com>"]
packages = [ { include = "tmo" } ]

[tool.poetry.scripts]
tmo = "tmo.main:app"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"
tortoise-orm = "^0.20.0"
pydantic = "^2.5.2"
uvicorn = "^0.24.0.post1"
sqlmodel = "^0.0.14"
fastapi = "^0.108.0"
psycopg = "^3.1.14"
typer = "^0.9.0"
httpx = "^0.26.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.18.1"
rich = "^13.7.0"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.1"
pudb = "^2023.1"
pylint = "^3.0.2"
ruff = "^0.1.7"
nest-asyncio = "^1.5.8"
watchfiles = "^0.21.0"
pre-commit = "^3.5.0"
pygments = "^2.17.2"
types-pygments = "^2.17.0.0"
shandy-sqlfmt = "^0.21.1"

[tool.poetry.group.load.dependencies]
openpyxl = "^3.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.mypy]
explicit_package_bases = true

[tool.pylint."BASIC"]
allowed-redefined-builtins = [
    "id",
]

good-names = [
    "_Base_Model",
    "_Subscriber_Bill_Link",
]

[tool.pylint."FORMAT"]
max-line-length = 120
disable = [
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-function-docstring",
]
