[project]
name = "tmo"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
authors = [{name="Brendan Cazier", email = "520246+cazier@users.noreply.github.com"}]
dependencies = [
    "fastapi>=0.115.0",
    "httpx>=0.27.2",
    "jinja2>=3.1.4",
    "psycopg[binary]>=3.2.3",
    "sqlmodel>=0.0.22",
    "typer>=0.12.5",
    "uvicorn>=0.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["tmo"]

[project.scripts]
tmo = "tmo.main:app"

[project.optional-dependencies]
pretty = [
    "pygments>=2.18.0",
    "shandy-sqlfmt>=0.23.2",
]
load = [
    "openpyxl>=3.1.5",
]
testing = [
    "coverage>=7.6.1",
    "pytest>=8.3.3",
]


[tool.uv]
dev-dependencies = [
    "faker>=30.1.0",
    "ipython>=8.28.0",
    "isort>=5.13.2",
    "mypy>=1.11.2",
    "pdbr>=0.8.9",
    "pre-commit>=3.8.0",
    "pygments>=2.18.0",
    "rich>=13.9.2",
    "ruff>=0.6.9",
    "shandy-sqlfmt>=0.23.2",
    "watchfiles>=0.24.0",
]

[tool.ruff]
line-length = 120

[tool.coverage.run]
omit = [
  "utilities/*"
]

[tool.isort]
line_length = 120
profile = "black"
<<<<<<< HEAD
=======

[tool.mypy]
strict = true
explicit_package_bases = true

[tool.poetry]
name = "tmo"
version = "1.0.0"
description = ""
authors = ["Brendan Cazier <520246+cazier@users.noreply.github.com>"]
packages = [{include = "tmo"}]

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.3"
uvicorn = "^0.29.0"
sqlmodel = {version = "^0.0.18", extras = ["shandy-sqlfmt", "pygments"]}
fastapi = "^0.111.0"
psycopg = "^3.1.18"
typer = "^0.12.3"
httpx = "^0.27.0"
pygments = {version = "^2.17.2", optional = true}
shandy-sqlfmt = {version = "^0.21.3", optional = true}
pydantic-settings = "^2.3.4"

[tool.poetry.extras]
sqlmodel = ["pygments", "shandy-sqlfmt"]

[tool.poetry.group.dev.dependencies]
ipython = "^8.24.0"
pre-commit = "^3.7.0"
rich = "^13.7.1"
watchfiles = "^0.21.0"
pygments = "^2.17.2"
shandy-sqlfmt = "^0.21.3"
faker = "^25.0.1"
pdbr = "^0.8.8"

[tool.poetry.group.linters.dependencies]
types-pygments = "^2.17.0.20240310"
mypy = "^1.10.0"
pylint = "^3.1.0"
ruff = "^0.4.3"
black = "^24.4.2"
isort = "^5.13.2"

[tool.poetry.group.load.dependencies]
openpyxl = "^3.1.2"

[tool.poetry.group.testing.dependencies]
pytest = "^8.2.0"
coverage = "^7.5.0"

[tool.poetry.scripts]
tmo = "tmo.main:app"

[tool.pylint."BASIC"]
allowed-redefined-builtins = [
  "id"
]
good-names = [
  "_Base_Model",
  "_Subscriber_Bill_Link"
]

[tool.pylint."FORMAT"]
max-line-length = 120
disable = [
  "missing-class-docstring",
  "missing-module-docstring",
  "missing-function-docstring"
]

[tool.ruff]
line-length = 120
>>>>>>> a15f0af (New package)
