name: CI/CD
on:
  push:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only main,linters
      # - run: poetry run mypy tmo
      - run: poetry run pylint tmo
      - run: poetry run black --check tmo
      - run: poetry run isort --check tmo

  coverage:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install poetry
      - run: poetry install --only main,testing --extras sqlmodel
      - run: poetry run coverage run -m pytest tests

      # - uses: cazier/actions/coverage@v1
      #   id: coverage
      #   with:
      #     coverage_file: coverage.out
      #     secret: ${{ secrets.CODECOV_TOKEN }}
